# Generated by Django 4.2.5 on 2023-09-29 12:11

import django.contrib.auth.models
from django.db import migrations
import social_api.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_sandboxed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', social_api.users.models.CustomUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
