# Generated by Django 4.2.5 on 2023-10-04 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
